# Generated by Django 5.1.1 on 2024-10-08 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroevento',
            name='codigo_registro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
