# Generated by Django 5.1.1 on 2024-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_registroevento_codigo_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroevento',
            name='numero_ticket',
            field=models.CharField(max_length=10),
        ),
    ]
