# Generated by Django 5.1.1 on 2024-10-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_registroevento_numero_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='es_gratuito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_normal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='precio_vip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
